name := "security-lab"
kubeconfig := env_var('HOME') + "/.kube/configs/" + name + ".yaml"

# Create kubernetes cluster
init:
    kind create cluster \
        --name {{ name }} \
        --config kind.yaml \
        --kubeconfig {{ kubeconfig }}

# Deploy artifacts
deploy:
    skaffold deploy

# Switch kubernetes context
switch:
    kubie ctx kind-security-lab

# Check status of pods, nodes, and middlewares
check:
    ./scripts/check.bash

# Destroy kubernetes cluster
destroy:
    kind delete cluster --name {{ name }}
