name := "security-lab"

# Create kubernetes cluster
init:
    kind create cluster \
        --name {{ name }} \
        --config kind.yaml
    kubectx -u

# Deploy artifacts
deploy:
    skaffold deploy

# Switch kubernetes context
switch:
    kubectx kind-security-lab

# Check status of pods, nodes, and middlewares
check:
    ./scripts/check.bash

# Destroy kubernetes cluster
destroy:
    kind delete cluster --name {{ name }}
