# General
export TMUX_POWERLINE_PATCHED_FONT_IN_USE="true"
export TMUX_POWERLINE_THEME="tokyonight"
export TMUX_POWERLINE_DIR_USER_THEMES="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-powerline/themes"

export TMUX_POWERLINE_STATUS_VISIBILITY="on"
export TMUX_POWERLINE_WINDOW_STATUS_LINE="0"
export TMUX_POWERLINE_STATUS_INTERVAL="1"
export TMUX_POWERLINE_STATUS_JUSTIFICATION="centre"

export TMUX_POWERLINE_STATUS_LEFT_LENGTH="100"
export TMUX_POWERLINE_STATUS_RIGHT_LENGTH="100"

# tmux_session_info.sh
export TMUX_POWERLINE_SEG_TMUX_SESSION_INFO_FORMAT="#S"
