#!/bin/bash

if [[ $1 == -t ]] ||
  [[ $2 == TYPE=crypto_LUKS ]] ||
  [[ $3 == -s ]] ||
  [[ $4 == UUID ]] ||
  [[ $5 == -o ]] ||
  [[ $6 == value ]]; then
  echo xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
else
  /usr/bin/blkid "$@"
fi
