extends:
  - "@commitlint/config-conventional"
rules:
  scope-enum:
    - 2
    - always
    - - apm
      - applications
      - atuin
      - bat
      - btop
      - claude
      - cz
      - docker
      - espanso
      - fastfetch
      - firefox
      - fontconfig
      - gh
      - gh-dash
      - ghostty
      - git
      - glzr
      - gnupg
      - gtk
      - herdr
      - hunk
      - hushlogin
      - hypr
      - k9s
      - kanshi
      - kube
      - kvantum
      - lazydocker
      - lazygit
      - lua
      - luacheck
      - mimeapps
      - mise
      - mozilla
      - mpv
      - msf4
      - neovide
      - nono
      - nvim
      - nwg-look
      - opencode
      - p10k
      - pet
      - quickshell
      - rofi
      - rofimoji
      - rtk
      - rumdl
      - rustscan
      - satty
      - sheldon
      - sqlfluff
      - stylelint
      - stylua
      - swaync
      - systemd
      - tealdeer
      - tmux
      - tmux-powerline
      - tmuxp
      - tokscale
      - translate-shell
      - tridactyl
      - user-dirs
      - uwsm
      - visidata
      - waybar
      - wezterm
      - wlogout
      - wob
      - worktrunk
      - wsl
      - xh
      - yamlfmt
      - yamllint
      - yasb
      - yay
      - yazi
      - zathura
      - zsh
      - zsh-abbr
      - deps # chore
