extends: default
rules:
  comments:
    min-spaces-from-content: 1
  document-start:
    present: false
ignore: |
  test/templates/*.yaml
  misc/security-lab/charts/*/templates/*.yaml
  misc/security-lab/charts/*/templates/tests/*.yaml
