pre = "*-alpha"
scopes = [
  "agents",
  "applications",
  "atuin",
  "bat",
  "btop",
  "cz",
  "docker",
  "espanso",
  "fastfetch",
  "firefox",
  "fontconfig",
  "gh",
  "ghostty",
  "git",
  "glzr",
  "gnupg",
  "gtk",
  "herdr",
  "hushlogin",
  "hypr",
  "k9s",
  "kanshi",
  "kube",
  "kvantum",
  "lazydocker",
  "lazygit",
  "lua",
  "luacheck",
  "mimeapps",
  "mise",
  "mozilla",
  "mpv",
  "msf4",
  "neovide",
  "nvim",
  "nwg-look",
  "opencode",
  "p10k",
  "pet",
  "quickshell",
  "rofi",
  "rofimoji",
  "rtk",
  "rumdl",
  "rustscan",
  "satty",
  "sheldon",
  "sqlfluff",
  "stylelint",
  "stylua",
  "swaync",
  "systemd",
  "tealdeer",
  "tmux",
  "tmux-powerline",
  "tmuxp",
  "tokscale",
  "translate-shell",
  "tridactyl",
  "user-dirs",
  "uwsm",
  "visidata",
  "waybar",
  "wezterm",
  "wlogout",
  "wob",
  "worktrunk",
  "wsl",
  "xh",
  "yamlfmt",
  "yamllint",
  "yasb",
  "yay",
  "yazi",
  "zathura",
  "zsh",
  "zsh-abbr",
  # old
  "aicommits",
  "asdf",
  "bash",
  "bluetuith",
  "bottom",
  "fish",
  "go",
  "gtk-4.0",
  "gtkrc-2.0",
  "home-manager",
  "keyd",
  "kubie",
  "markdownlint",
  "markdownlint-cli2",
  "mcphub",
  "ncspot",
  "nix",
  "nnn",
  "pacman",
  "psd",
  "qmk",
  "rtx",
  "sql-formatter",
  "starship",
  "swappy",
  "sway",
  "wt",
]
