---
apiVersion: skaffold/v4beta3
kind: Config
deploy:
  helm:
    releases:
      - name: kalilinux
        chartPath: ./charts/pentest-machine/
        namespace: pentest-machine
        createNamespace: true
      - name: parrot
        chartPath: ./charts/pentest-machine/
        namespace: pentest-machine
        createNamespace: true
        setValues:
          name: parrot
          image.repository: parrotsec/security
      - name: blackarch
        chartPath: ./charts/pentest-machine/
        namespace: pentest-machine
        createNamespace: true
        setValues:
          name: blackarch
          image.repository: blackarchlinux/blackarch
      - name: juice-shop
        repo: https://charts.securecodebox.io
        remoteChart: juice-shop
        namespace: vuln-web-app
        createNamespace: true
      - name: webgoat
        chartPath: ./charts/webgoat/
        namespace: vuln-web-app
        createNamespace: true
      - name: dvga
        chartPath: ./charts/dvga/
        namespace: vuln-web-app
        createNamespace: true
