[".local/share/fcitx5/themes"]
type = "archive"
url = "https://github.com/Reverier-Xu/Fluent-fcitx5/archive/refs/tags/v0.4.0.tar.gz"
exact = true
stripComponents = 1
exclude = ["*/imgs", "*/README.md"]

[".local/bin/grimblast"]
type = "file"
# renovate: depName=hyprwm/contrib branch=main
url = "https://raw.githubusercontent.com/hyprwm/contrib/3dcbce715ae8b93107fa8632db15bf976862a573/grimblast/grimblast"
executable = true

[".local/bin/scratchpad"]
type = "file"
# renovate: depName=hyprwm/contrib branch=main
url = "https://raw.githubusercontent.com/hyprwm/contrib/3dcbce715ae8b93107fa8632db15bf976862a573/scratchpad/scratchpad"
executable = true

[".local/bin/cliphist-rofi-img"]
type = "file"
url = "https://raw.githubusercontent.com/sentriz/cliphist/refs/tags/v0.7.0/contrib/cliphist-rofi-img"
executable = true

[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
