matches:
  - trigger: ";d "
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y/%m/%d"
  - trigger: ";t "
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%H:%M"
