# Disable default build options
BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
AUDIO_ENABLE = no
SWAP_HANDS_ENABLE = no
RGB_MATRIX_ENABLE = no
DYNAMIC_MACRO_ENABLE = no

# Enable build options
TAP_DANCE_ENABLE = yes
