name: main
"on": push
jobs:
  chezmoi:
    runs-on: ubuntu-26.04
    container:
      image: archlinux:base-20260705.0.552420
    steps:
      - uses: actions/checkout@main
      - name: Generate keyring and download database file
        run: pacman-key --init && pacman -Sy
      - name: Install git command for chezmoiexternal git-repo type
        run: pacman -S --noconfirm git
      - name: Install dotfiles manager
        run: pacman -S --noconfirm chezmoi
      - name: Deploy dotfiles
        run: |
          chezmoi init --branch "${{ github.ref_name }}" n4vysh && chezmoi apply
          ls -l ~/.*
  pre-commit:
    runs-on: ubuntu-26.04
    container:
      image: archlinux:base-20260705.0.552420
    steps:
      - name: Generate keyring and download database file
        run: pacman-key --init && pacman -Sy
      - name: Install packages for test
        run: |
          sed \
            -i \
            -e 's/^#ParallelDownloads = .*$/ParallelDownloads = 20/' \
            /etc/pacman.conf
          sed \
            -i \
            -e 's/-march=x86-64 -mtune=generic/-march=native/' \
            -e "/^#MAKEFLAGS=\"-j2\"$/s/-j2/-j$(nproc)/" \
            -e '/^COMPRESSZST/s/zstd -c/zstd -1 --threads=0 -c/' \
            /etc/makepkg.conf
          pacman -S --noconfirm \
            pre-commit \
            prettier \
            rumdl \
            yamlfmt \
            yamllint \
            shellcheck \
            zsh \
            selene \
            stylua \
            editorconfig-checker \
            typos \
            taplo \
            shellharden \
            shfmt \
            git
      - uses: actions/checkout@main
      - name: Set safe directory for submodule clone
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Run pre-commit
        run: SKIP=hyprland,bats pre-commit run -a
  cocogitto:
    runs-on: ubuntu-26.04
    container:
      image: archlinux:base-20260705.0.552420
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate keyring and download database file
        run: pacman-key --init && pacman -Sy
      - name: Install cocogitto command
        run: pacman -S --noconfirm git cocogitto
      - name: Validate current commit (last commit)
        run: cog check HEAD~1..HEAD
