name: main
"on": pull_request
jobs:
  cocogitto:
    runs-on: ubuntu-26.04
    container:
      image: archlinux:base-20260705.0.552420
    permissions:
      contents: read
    steps:
      - name: Generate keyring and download database file
        run: pacman-key --init && pacman -Sy
      - name: Install cocogitto command
        run: pacman -S --noconfirm git cocogitto
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate PR commits
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: cog check "$BASE_SHA..$HEAD_SHA"
